create table if not exists public.events (
  id bigint generated by default as identity primary key,
  type text not null,
  user_id text,
  commit_hash text,
  timestamp bigint,
  version text,
  queued_at bigint,
  retry_count integer,
  received_at timestamptz not null default now()
);

create index if not exists idx_events_type on public.events (type);
create index if not exists idx_events_user on public.events (user_id);
create index if not exists idx_events_received_at on public.events (received_at desc);

alter table public.events enable row level security;

drop policy if exists events_insert_service on public.events;
create policy events_insert_service on public.events
  for insert to service_role with check (true);

drop policy if exists events_select_service on public.events;
create policy events_select_service on public.events
  for select to service_role using (true);

grant insert, select on public.events to service_role;

do $$
begin
  alter publication supabase_realtime add table public.events;
exception
  when duplicate_object then null;
end;
$$;
